== ri-collection-explicit-feedback-twitter image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]

This microservice was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Technical description
=== What does the microservice do
The goal of this microservice is to collect data from Twitter. In particular, this service collects tweets that mention a given account. The response contains a list of tweets in JSON format.

=== Which technologies are used
- Docker (-> https://www.docker.com/)
- Go (-> https://github.com/golang/go)
- Anaconda (-> https://github.com/ChimeraCoder/anaconda)

=== How to install it
ri-collection-explicit-feedback-twitter requires a installed distribution of Go link:[https://golang.org/doc/install]

Run the following commands to start the microservice:

. docker build -t ri-collection-explicit-feedback-twitter .

. docker run -e "CONSUMER_KEY=<YOUR_CONSUMER_KEY>" -e "CONSUMER_SECRET=<YOUR_CONSUMER_SECRET>" -e "ACCESS_KEY=<YOUR_ACCESS_KEY>" -e "ACCESS_SECRET=<YOUR_ACCESS_SECRET>" -p 9624:9624 ri-collection-explicit-feedback-twitter

The required access tokens of the Docker environment variables can be generated on the official Twitter developer page: https://developer.twitter.com/en/docs/basics/authentication/guides/access-tokens.html

=== How to use it (high-level description)
The API is documented by using Swagger2:

- link:http://217.172.12.199/registry/#/services/ri-collection-explicit-feedback-twitter[Rendered Documentation]

=== Notes for developers 
None.

=== Sources
None.

== How to contribute
See OpenReq project contribution link:https://github.com/OpenReqEU/OpenReq/blob/master/CONTRIBUTING.md[Guidlines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).